### ISSUE TITLE
KeyError: 'flashcards' on retrieving student profile

### ISSUE THREAD

**Issue by bgins** [ereadingtool/ereadingtool#159]
When the frontend attempts to retrieve a student profile, the server fails with a KeyError: 'flashcards' error and returns a 500 Internal Error.

The client makes a GET request to an endpoint something like `http://localhost:8000/api/student/1/`. The expectation is the server returns a student profile, but instead the server errs.

To reproduce, login as a student on the `upgrade/staging` branch. The frontend will attempt to fetch the student profile immediately after loading the profile page. The error can be observed at the console with Django DEBUG set to True and in the browser dev tools.

**Comment by jdelamare** [comment]
The error is fixed but not in a respectable way. Looking to figure out where best to initialize `flashcards` and `performance_report` so that the calls to `.pop()` don't crash the backend.

Hot patch commit here: https://github.com/ereadingtool/ereadingtool/commit/71524b6c1d0f9b14fa845d47071c1f548d0e80c5

**Comment by jdelamare** [comment]
The issue seems to be that neither `flashcards` nor `performance_report` are fields in the dict returned by [`to_dict()`](https://github.com/ereadingtool/ereadingtool/blob/d98e918f91b62dae8953738dbd8df5e48e09cb52/user/student/models.py#L48) which is called immediately before the [`.pop()`](https://github.com/ereadingtool/ereadingtool/blob/d98e918f91b62dae8953738dbd8df5e48e09cb52/user/views/student.py#L234)

**Comment by jdelamare** [comment]
I can't seem to hit this endpoint from the stable version on my local machine. I guess the patch will have to do for now until we need more functionality from the [`StudentAPIView`](https://github.com/ereadingtool/ereadingtool/blob/d98e918f91b62dae8953738dbd8df5e48e09cb52/user/views/student.py#L214)

**Comment by jdelamare** [comment]
addressed in PR #185
