### ISSUE TITLE
Reduce load time of instructor text list view

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#30]
The page at [/admin/texts/](https://stepstoadvancedreading.org/admin/texts/) is taking too long to return a list of texts.

**Comment by bgins** [comment]
Work on the client side for this has started by removing `uri` and `write_locker`. The next step is to remove fields that are sent by the backend but not used by the client.

Let's remove `uri`, `write_locker`, `introduction`, `conclusion`, `source`, `last_modified_by` from the `/api/text` endpoint when called with a GET. (This endpoint may take query params as filters.)

Note that we should not change the data returned by `api/text/<text_id>` because we use that to retrieve a text for reading purposes. Similarly, methods other than GET on `/api/text` should not change.

**Comment by jdelamare** [comment]
We're moving quickly now!
